### ISSUE TITLE
Use 0.0.0.0/0 as the inbound IP source range or better document how to open the VM to another IP 

### ISSUE THREAD

**Issue by loicmathieu** [Zenika/infra4lab#11]
Currently, the VM are created with a security group that restrict the inbound IP to the IP that created them !
So only the trainer can access the VM.

As the IP rules can be difficult (corporate proxy, 4G connection, ...) I propose to, by default, create the security group with the 0.0.0.0/0 inbound ip range and document how to restrict it if needed.
Those VMs are for training purpose, they didn't need to be secured by default.

**Comment by zigarn** [comment]
There is the [`authorized_ips` extra option](https://github.com/Zenika/infra4lab#session-extra-configuration) available for this situation.

Not a big fan of the idea to open wildly, but agree that the documentation could warn on this behavior and highlight this option.

**Comment by loicmathieu** [comment]
I don't understand why the VM are not open by default. 
They are ephemeral VMs for training purpose they don't need to be very secure and they are already secured by an SSH key!
For example, Strigo's VMs are open...

Moreover, it will be difficult to know which IPs to open before a training so in most cases we will end up opening to all IP.

**Comment by zigarn** [comment]
SSH is secured, but not the other services that the trainees may or have to launch during the training. Some of them can have vulnerabilities or simply use default credentials, and this could compromise the VM.

I improved the documentation on the `authorized_ips` configuration (simply asking trainees for the result of https://ifconfig.me has never been difficult in my experience).
I also added an option to open the VMs access worldwide, but disagree to make it the default.

**Comment by loicmathieu** [comment]
I'm having a hard time to see how it can compromise ephemeral VMs used for training and why it is important.
![image](https://user-images.githubusercontent.com/1819009/91280025-828af480-e786-11ea-9cd7-58a9d3785a5e.png)

Threat is low, Vulnerability is low and Asset has no value ...

Anyway, I think most trainer will open it worldwide (as professionals like Strigo does), mostly because as a trainer, I prefere to have everything setup before I start the training, and it's already hard to have the correct list of the trainnee emails so having the IP range that needs a call to IT support ...

But it's your choice, it's just another thing to not forget ...

**Comment by zigarn** [comment]
Fixed by PR #12
